# Generated by Django 4.1 on 2022-09-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=30)),
                ('isin', models.CharField(max_length=12)),
                ('asset_group', models.CharField(choices=[('미국 주식', '미국 주식'), ('미국섹터 주식', '미국섹터 주식'), ('선진국 주식', '선진국 주식'), ('신흥국 주식', '신흥국 주식'), ('전세계 주식', '전세계 주식'), ('부동산 / 원자재', '부동산 / 원자재'), ('채권 / 현금', '채권 / 현금')], max_length=30)),
            ],
        ),
    ]
